# golangci-lint configuration
# https://golangci-lint.run/docs/configuration/file/

version: "2"

linters:
  # Use default linters (errcheck, govet, ineffassign, staticcheck, unused)
  default: standard

  settings:
    errcheck:
      # Don't check errors from Close, Stop, Sync in defer statements
      exclude-functions:
        - (*os.File).Close
        - (*os.File).Sync
        - (io.Closer).Close

  exclusions:
    # Exclude errcheck in test files (common pattern)
    rules:
      - path: _test\.go
        linters:
          - errcheck
    # Enable common exclusion presets
    presets:
      - std-error-handling
      - common-false-positives
